name: "coverage"
on:
  push:
    branches:
      - master
      - main
      - production
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
